UsingEntityFramework/LiberoRentACar/LiberoRentACarWeb/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LiberoRentACarClasses;

namespace LiberoRentACarWeb.Models
{
    public class CarController : Controller
    {
        private RentSysDbContext db = new RentSysDbContext();

        // GET: /Car/
        public ActionResult Index()
        {
            var cars = db.Cars.Include(c => c.Model);
            return View(cars.ToList());
        }

        // GET: /Car/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        //public PartialViewResult DetailsChild(int? id)
        //{
        //    Car car = db.Cars.Find(id);
        //    return PartialView("_Details", car);
        //}

        // GET: /Car/Create
        public ActionResult Create()
        {
            ViewBag.ModelID = new SelectList(db.Models, "ModelID", "Name");
            return View();
        }

        // POST: /Car/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="CarID,ModelID,Year,Mileage,CarCor,LicensePlate,IsAutomatic,Rank,Price")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.Cars.Add(car);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ModelID = new SelectList(db.Models, "ModelID", "Name", car.ModelID);
            return View(car);
        }

        // GET: /Car/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            ViewBag.ModelID = new SelectList(db.Models, "ModelID", "Name", car.ModelID);
            return View(car);
        }

        // POST: /Car/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="CarID,ModelID,Year,Mileage,CarCor,LicensePlate,IsAutomatic,Rank,Price")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ModelID = new SelectList(db.Models, "ModelID", "Name", car.ModelID);
            return View(car);
        }

        // GET: /Car/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // POST: /Car/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Car car = db.Cars.Find(id);
            db.Cars.Remove(car);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UsingEntityFramework/LiberoRentACar/LiberoRentACarWeb/Controllers/RentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LiberoRentACarClasses;

namespace LiberoRentACarWeb.Controllers
{
    public class RentController : Controller
    {
        private RentSysDbContext db = new RentSysDbContext();

        // GET: /Rent/
        public ActionResult Index()
        {
            var rents = db.Rents.Include(r => r.Car).Include(r => r.Client);
            return View(rents.ToList());
        }

        // GET: /Rent/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rent rent = db.Rents.Find(id);
            if (rent == null)
            {
                return HttpNotFound();
            }
            return View(rent);
        }

        // GET: /Rent/Create
        public ActionResult Create()
        {
            ViewBag.CarID = new SelectList(db.Cars, "CarID", "LicensePlate");
            ViewBag.UserID = new SelectList(db.Users, "UserID", "Name");
            return View();
        }

        // POST: /Rent/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="RentID,CarID,UserID,PickupDate,ReturnDate,MileageInit,Price")] Rent rent)
        {
            if (ModelState.IsValid)
            {
                db.Rents.Add(rent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CarID = new SelectList(db.Cars, "CarID", "LicensePlate", rent.CarID);
            ViewBag.UserID = new SelectList(db.Users, "UserID", "Name", rent.UserID);
            return View(rent);
        }

        // GET: /Rent/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rent rent = db.Rents.Find(id);
            if (rent == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarID = new SelectList(db.Cars, "CarID", "LicensePlate", rent.CarID);
            ViewBag.UserID = new SelectList(db.Users, "UserID", "Name", rent.UserID);
            return View(rent);
        }

        // POST: /Rent/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="RentID,CarID,UserID,PickupDate,ReturnDate,MileageInit,Price")] Rent rent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CarID = new SelectList(db.Cars, "CarID", "LicensePlate", rent.CarID);
            ViewBag.UserID = new SelectList(db.Users, "UserID", "Name", rent.UserID);
            return View(rent);
        }

        // GET: /Rent/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rent rent = db.Rents.Find(id);
            if (rent == null)
            {
                return HttpNotFound();
            }
            return View(rent);
        }

        // POST: /Rent/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rent rent = db.Rents.Find(id);
            db.Rents.Remove(rent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UsingEntityFramework/LiberoRentACar/LiberoRentACarWeb/Views/Shared/_CarDetail.cshtml
@model LiberoRentACarClasses.Car

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mileage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mileage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarCor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarCor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LicensePlate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LicensePlate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAutomatic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAutomatic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rank)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rank)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>

UsingEntityFramework/LiberoRentACar/LiberoRentACarWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Libero Rent A Car</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Libero Rent A Car", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Cars", "Index", "Car")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Rents", "Index", "Rent")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Libero Rent A Car</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>